CXX = g++
CXX_FLAGS = -std=c++11 -g

all:
	echo "$(CXX) -o sorting_comparison"
merge_sort_int_test:
	$(CXX) $(CXX_FLAGS) merge_sort_int_test.cpp -o merge_sort_int_test
clean:
	rm -rf *~ merge_sort_int_test
